prometheus:
  serviceAccount:
    create: true
    name: ${amp_sa}
  prometheusSpec:
    serviceAccountName: ${amp_sa}
    remoteWrite:
      - url: ${amp_remotewrite_url}
        sigv4:
          region: ${region}
        queueConfig:
          maxSamplesPerSend: 1000
          maxShards: 200
          capacity: 2500
    retention: 5h
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
    # Scrape Cost metrics for Kubecost add-on
    # additionalScrapeConfigs:
    #   - job_name: kubecost
    #     honor_labels: true
    #     scrape_interval: 1m
    #     scrape_timeout: 10s
    #     metrics_path: /metrics
    #     scheme: http
    #     dns_sd_configs:
    #       - names:
    #           - kubecost-cost-analyzer.kubecost.svc
    #         type: 'A'
    #         port: 9003
alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: null
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password
  service:
    port: ${grafana_service_port}
  serviceAccount:
    create: true
    name: grafana-sa
  grafana.ini:
    aws:
      allowed_auth_providers: ec2_iam_role
      assume_role_enabled: true
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  plugins:
    - grafana-amazonprometheus-datasource
  additionalDataSources:
    - name: Amazon-Managed-Prometheus
      type: grafana-amazonprometheus-datasource
      access: proxy
      url: ${amp_url}
      isDefault: true
      jsonData:
        authType: ec2_iam_role
        defaultRegion: ${region}
        sigV4Region: ${region}
      editable: true
